-- Soul2SoulsJazz shop seed — kept in sync with src/data/shop.ts (21 products,
-- grid order, real descriptions). Re-runnable: upserts on slug.
insert into products (slug, name, price_cents, description, image, sort_order, in_stock) values
  ('24-oz-mia-recycled-acrylic-tumbler', '24 oz. Mia Recycled Acrylic Tumbler', 1995, 'Experience the perfect blend of style and sustainability—this tumbler is made entirely from 100% recycled acrylic, making it an eco-friendly choice for your drinkware collection. Keep your cold drinks at the optimal temperature with its double-wall construction that not only maintains your beverage''s chill but also significantly reduces condensation on the outside, ensuring a comfortable grip. Designed for those on the move, the slender shape fits snugly into standard cup holders, while the swivel lid and angled straw prevent spills during transport, ensuring your hydration is as convenient as it is secure.', '/images/shop/24-oz-mia-recycled-acrylic-tumbler.webp', 1, true),
  ('dj-perry-remix-gildan-softstyle-jersey-t-shirt', 'DJ Perry Remix – Gildan Softstyle Jersey T-shirt', 3500, 'Trendy and budget-friendly – what''s not to love about this style? Try this on for size: a lightweight and comfortable fabric with an exciting color palette', '/images/shop/dj-perry-remix-gildan-softstyle-jersey-t-shirt.webp', 2, true),
  ('hoodie-ladies-white-front-logo', 'Hoodie Ladies White (Front Logo)', 8495, '', '/images/shop/hoodie-ladies-white-front-logo.webp', 3, true),
  ('hoodie-ladies-white-logo-on-back', 'Hoodie Ladies White (logo on back)', 8495, '', '/images/shop/hoodie-ladies-white-logo-on-back.webp', 4, true),
  ('hoodie-mens-black-white-tie-dye', 'Hoodie Mens Black & White Tie Dye', 8400, '', '/images/shop/hoodie-mens-black-white-tie-dye.webp', 5, true),
  ('ladies-curved-hem-tri-blend-long-sleeve-tunic-t-shirt', 'Ladies Curved Hem Tri-Blend Long Sleeve Tunic T-shirt', 5700, 'Women''s Tri-Blend Long Sleeve Tunic T-shirt offers an irresistible combination of comfort, style, and functionality. With a soft tri-blend fabric, raglan sleeves, and a fashionable long length, this tunic is perfect for any casual outing or relaxed office look. The wider rib neck adds a touch of sophistication while maintaining a laid-back vibe. A perfect addition to any wardrobe, it combines style with comfort in every wear.', '/images/shop/ladies-curved-hem-tri-blend-long-sleeve-tunic-t-shirt.webp', 6, true),
  ('laser-engraved-15-oz-stemless-wine-glass-set-of-2', 'Laser Engraved 15 oz. Stemless Wine Glass (Set of 2)', 4995, 'Elegant stemless wine glass set with laser-engraved Soul2Souls Jazz logo. Enjoy your favorite wines in style! The customizable Laser Engraved 15 oz. Stemless Wine Glass set features a sleek design and laser-engraved personalization that''s perfect for special occasions, corporate gifts, or personal use.', '/images/shop/laser-engraved-15-oz-stemless-wine-glass-set-of-2.webp', 7, true),
  ('laser-engraved-marble-and-bamboo-coasters-set-of-4', 'Laser Engraved Marble and Bamboo Coasters (Set of 4)', 5295, 'Introducing the Laser Engraved Marble and Bamboo Coasters, a set of 4 perfect for the discerning homeowner or event host. Featuring a blend of marble''s natural beauty and bamboo''s warm tones, these coasters add sophisticated elegance to any setting while protecting your surfaces.', '/images/shop/laser-engraved-marble-and-bamboo-coasters-set-of-4.webp', 8, true),
  ('s2s-10-oz-glass-coffee-mug', 'S2S 10 oz. Glass Coffee Mug', 2495, 'Whether you''re sipping hot cocoa by the fire, serving up a round of drinks, or toasting your friends, you''ll want to do it with this unique style that can hold both hot and cold drinks.', '/images/shop/s2s-10-oz-glass-coffee-mug.webp', 9, true),
  ('s2s-bio-washed-hat-engraved-circle-faux-leather-patch', 'S2S Bio-Washed Hat – Engraved Circle Faux Leather Patch', 4500, 'Cap off your look! The Engraved Bio-Washed Hat – Circle Faux Leather Patch is treated to give it a slightly broken-in feel. This low-profile hat comes with a pre-curved visor and an adjustable buckle closure.', '/images/shop/s2s-bio-washed-hat-engraved-circle-faux-leather-patch.webp', 10, true),
  ('s2s-canvas-tote-bag', 'S2S Canvas Tote Bag', 5000, 'Tackle every convention in style with this durable tote! The Starboard Large Cotton Canvas Tote Bag combines attractive looks with functional storage. This rugged tote bag is perfect for events or getaways with friends and has plenty of space for everything you need for a successful trip!

Size 13″ H x 20.5″ W x 7″ D', '/images/shop/s2s-canvas-tote-bag.webp', 11, true),
  ('s2s-dj-steppin-softstyle-jersey-t-shirt', 'S2S DJ Steppin'' Softstyle Jersey T-shirt', 4800, 'Trendy and budget-friendly – what''s not to love about this style? Try this on for size: a lightweight and comfortable fabric with an exciting color palette.', '/images/shop/s2s-dj-steppin-softstyle-jersey-t-shirt.webp', 12, true),
  ('s2s-jazz-logo-semi-fitted-t-shirt', 'S2S Jazz Logo Semi-Fitted T Shirt', 3495, 'Comfortable fabric with an exciting color palette. An excellent choice for your next event', '/images/shop/s2s-jazz-logo-semi-fitted-t-shirt.webp', 13, true),
  ('s2s-ladies-curved-hem-adidas-upf-50-performance-shirt', 'S2S Ladies Curved Hem Adidas UPF 50 Performance Shirt', 6895, 'This performance t-shirt will not disappoint! Stay dry, protected from the sun and looking great in this Adidas performance t-shirt. High-quality fabric with subtle styling details makes this a shirt you will love to wear!', '/images/shop/s2s-ladies-curved-hem-adidas-upf-50-performance-shirt.webp', 14, true),
  ('s2s-ladies-flex-scoop-neck-t-shirt', 'S2S Ladies Flex Scoop Neck T-shirt', 4495, 'This Ladies'' Flex Scoop Neck T-shirt provides unmatched comfort and style with a touch of stretch for a flattering fit. Made from high-quality fabric, this t-shirt boasts a scoop neck design that complements any casual wardrobe. Its unique blend offers flexibility and maintains shape after wear and washing, ensuring it remains a staple in your daily attire.', '/images/shop/s2s-ladies-flex-scoop-neck-t-shirt.webp', 15, true),
  ('s2s-ladies-night-round-neck-t', 'S2S Ladies Night Round Neck T', 4100, 'This performance tee has UPF 50 sun protection and Dry Zone moisture wicking technology. It is lightweight and has either a removable or tag-free label. Combat the sun with this soft and stylish shirt. Breeze through your daily activities with this comfortable shirt that''s built to move with you.', '/images/shop/s2s-ladies-night-round-neck-t.webp', 16, true),
  ('s2s-ladies-v-neck-t-shirt', 'S2S Ladies V-Neck T Shirt', 4700, 'The perfect v-neck tee for a polished look!

Discover effortless style and exceptional comfort with the District Women''s Perfect Weight V-Neck T-shirt, designed to be your go-to garment for any occasion. Crafted from a blend of soft and lightweight materials, this T-shirt offers a flattering fit and promises lasting durability.', '/images/shop/s2s-ladies-v-neck-t-shirt.webp', 17, true),
  ('s2s-next-level-jersey-blend-t-shirt', 'S2S Next Level Jersey Blend T-shirt', 4500, 'Take your style to the Next Level in this contemporary style! Enjoy all-day comfort in this T Shirt – features a blend of cotton and polyester for a soft, breathable feel. Perfect for teams, events, or everyday wear, this t-shirt combines comfort with durability.', '/images/shop/s2s-next-level-jersey-blend-t-shirt.webp', 18, true),
  ('s2s-port-company-womens-upf-50-performance-shirt', 'S2S Port & Company Women''s UPF 50 Performance Shirt', 4800, 'This performance tee has UPF 50 sun protection and Dry Zone moisture wicking technology. The Port & Company Women''s UPF 50 Performance Shirt is the ideal companion for active women who want both style and protection. With its UPF 50 rating, it effectively shields you from harmful sun exposure and offers a flattering fit that moves with you, ensuring comfort and freedom throughout your day.', '/images/shop/s2s-port-company-womens-upf-50-performance-shirt.webp', 19, true),
  ('s2s-port-authority-tote-bag', 'S2S Port Authority Tote Bag', 4500, 'Medium Colorblock Cotton Tote Bag blends fashion with function, offering a stylish and practical solution for everyday needs. Its modern colorblock design adds a touch of trendiness, making it perfect for groups, events, or personal use. Whether you''re heading to the beach, store, or office, this tote is a reliable companion due to its robust structure and spacious capacity.', '/images/shop/s2s-port-authority-tote-bag.webp', 20, true),
  ('s2s-sport-tek-competitor-united-performance-jersey', 'S2S Sport-Tek Competitor United Performance Jersey', 5200, 'The Sport-Tek Competitor United Performance Jersey is made of lightweight poly fabric with PosiCharge technology that prevents our logo from fading. It is UPF 30+ and has contrasting color blocks on the shoulders.', '/images/shop/s2s-sport-tek-competitor-united-performance-jersey.webp', 21, true)
on conflict (slug) do update set
  name = excluded.name,
  price_cents = excluded.price_cents,
  description = excluded.description,
  image = excluded.image,
  sort_order = excluded.sort_order,
  in_stock = excluded.in_stock;
