/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PresskitRouteImport } from './routes/presskit'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as GalleryFullwidthRouteImport } from './routes/gallery-fullwidth'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop_.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PresskitRoute = PresskitRouteImport.update({
  id: '/presskit',
  path: '/presskit',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryFullwidthRoute = GalleryFullwidthRouteImport.update({
  id: '/gallery-fullwidth',
  path: '/gallery-fullwidth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop_/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery-fullwidth': typeof GalleryFullwidthRoute
  '/podcasts': typeof PodcastsRoute
  '/presskit': typeof PresskitRoute
  '/shop': typeof ShopRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery-fullwidth': typeof GalleryFullwidthRoute
  '/podcasts': typeof PodcastsRoute
  '/presskit': typeof PresskitRoute
  '/shop': typeof ShopRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery-fullwidth': typeof GalleryFullwidthRoute
  '/podcasts': typeof PodcastsRoute
  '/presskit': typeof PresskitRoute
  '/shop': typeof ShopRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop_/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/events'
    | '/gallery-fullwidth'
    | '/podcasts'
    | '/presskit'
    | '/shop'
    | '/checkout/success'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/events'
    | '/gallery-fullwidth'
    | '/podcasts'
    | '/presskit'
    | '/shop'
    | '/checkout/success'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/events'
    | '/gallery-fullwidth'
    | '/podcasts'
    | '/presskit'
    | '/shop'
    | '/checkout/success'
    | '/shop_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryFullwidthRoute: typeof GalleryFullwidthRoute
  PodcastsRoute: typeof PodcastsRoute
  PresskitRoute: typeof PresskitRoute
  ShopRoute: typeof ShopRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presskit': {
      id: '/presskit'
      path: '/presskit'
      fullPath: '/presskit'
      preLoaderRoute: typeof PresskitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery-fullwidth': {
      id: '/gallery-fullwidth'
      path: '/gallery-fullwidth'
      fullPath: '/gallery-fullwidth'
      preLoaderRoute: typeof GalleryFullwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop_/$slug': {
      id: '/shop_/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryFullwidthRoute: GalleryFullwidthRoute,
  PodcastsRoute: PodcastsRoute,
  PresskitRoute: PresskitRoute,
  ShopRoute: ShopRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
